import type { CaseStudy } from "@/lib/work";

export const labProjects: CaseStudy[] = [
  {
    slug: "flight-finder",
    company: "Flight Finder",
    role: "Firecrawl · Claude · Vercel",
    year: "2025",
    tags: ["AI", "Firecrawl", "Travel"],
    metric: "< 1 day",
    metricLabel: "build to deploy",
    summary: "A Firecrawl + Claude pipeline that scrapes airline deals and surfaces them in a clean, scannable UI.",
    thumbnail: "/images/lab/flight-finder-thumb.jpg",
    readTime: "",
    protected: false,
    sections: [],
  },
  {
    slug: "grammar-editor",
    company: "Grammar Editor",
    role: "Claude API · React · Vercel",
    year: "2025",
    tags: ["AI", "Writing", "Claude"],
    metric: "Real-time",
    metricLabel: "inline rewrites",
    summary: "A lightweight writing editor wired to the Claude API. Highlights grammar issues and suggests rewrites inline.",
    thumbnail: "/images/lab/grammar-editor-thumb.jpg",
    readTime: "",
    protected: false,
    sections: [],
  },
  {
    slug: "portfolio-chatbot",
    company: "Portfolio AI",
    role: "Claude API · Next.js",
    year: "2025",
    tags: ["AI", "Chatbot", "Portfolio"],
    metric: "~2 hrs",
    metricLabel: "build time",
    summary: "A conversational AI assistant trained on my background and work history, embedded directly in this portfolio.",
    thumbnail: "/images/lab/chatbot-thumb.jpg",
    readTime: "",
    protected: false,
    sections: [],
  },
];
